# Generated by Django 3.0.8 on 2023-03-14 07:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default2.jpg', upload_to=blog.models.user_directory_path),
        ),
    ]
